name: ROWDY
favicon: null
layout_spectrum: 0.21378252701833844
typography_spectrum: 0.3494565861765295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4046544588636607
  lightness: 0.22718626190908253
  saturation: 0.24235287494957447
  rhythmicContrast: 0.34378032060340047
purpose: []
